[2023-03-06 15:59:38.683227] ERROR: UserDao: 添加用例失败:__init__() missing 1 required positional argument: 'expected'
[2023-03-06 16:00:12.322166] ERROR: UserDao: 添加用例失败:name 'expected' is not defined
[2023-03-06 16:00:58.489822] ERROR: UserDao: 添加用例失败:name 'expected' is not defined
[2023-03-06 16:01:55.520880] ERROR: UserDao: 添加用例失败:name 'expected' is not defined
[2023-03-06 16:02:08.766462] ERROR: UserDao: 添加用例失败:name 'expected' is not defined
[2023-03-06 16:04:14.227694] ERROR: UserDao: 添加用例失败:name 'expected' is not defined
[2023-03-06 16:04:21.050543] ERROR: UserDao: 添加用例失败:name 'expected' is not defined
[2023-03-06 16:09:47.143643] ERROR: UserDao: 获取测试用例失败:name 'child' is not defined
[2023-03-06 16:35:59.358622] ERROR: UserDao: 获取测试用例失败:name 'child' is not defined
[2023-03-06 16:36:31.128235] ERROR: UserDao: 获取测试用例失败:name 'child' is not defined
[2023-03-12 09:39:52.577555] ERROR: UserDao: 查询项目:3失败,(mysql.connector.errors.ProgrammingError) 1054 (42S22): Unknown column 'project.app' in 'field list'
[SQL: SELECT project.id AS project_id, project.name AS project_name, project.owner AS project_owner, project.app AS project_app, project.created_at AS project_created_at, project.updated_at AS project_updated_at, project.deleted_at AS project_deleted_at, project.create_user AS project_create_user, project.update_user AS project_update_user, project.private AS project_private, project.description AS project_description 
FROM project 
WHERE project.id = %(id_1)s AND project.deleted_at IS NULL 
 LIMIT %(param_1)s]
[parameters: {'id_1': '3', 'param_1': 1}]
(Background on this error at: http://sqlalche.me/e/14/f405)
[2023-03-12 09:41:58.628241] ERROR: UserDao: 查询项目:3失败,(mysql.connector.errors.ProgrammingError) 1054 (42S22): Unknown column 'project.app' in 'field list'
[SQL: SELECT project.id AS project_id, project.name AS project_name, project.owner AS project_owner, project.app AS project_app, project.created_at AS project_created_at, project.updated_at AS project_updated_at, project.deleted_at AS project_deleted_at, project.create_user AS project_create_user, project.update_user AS project_update_user, project.private AS project_private, project.description AS project_description 
FROM project 
WHERE project.id = %(id_1)s AND project.deleted_at IS NULL 
 LIMIT %(param_1)s]
[parameters: {'id_1': '3', 'param_1': 1}]
(Background on this error at: http://sqlalche.me/e/14/f405)
[2023-03-12 10:44:22.108821] ERROR: UserDao: 查询项目:2失败,(mysql.connector.errors.ProgrammingError) 1054 (42S22): Unknown column 'project.app' in 'field list'
[SQL: SELECT project.id AS project_id, project.name AS project_name, project.owner AS project_owner, project.app AS project_app, project.created_at AS project_created_at, project.updated_at AS project_updated_at, project.deleted_at AS project_deleted_at, project.create_user AS project_create_user, project.update_user AS project_update_user, project.private AS project_private, project.description AS project_description 
FROM project 
WHERE project.id = %(id_1)s AND project.deleted_at IS NULL 
 LIMIT %(param_1)s]
[parameters: {'id_1': '2', 'param_1': 1}]
(Background on this error at: http://sqlalche.me/e/14/f405)
[2023-03-12 10:46:42.995756] ERROR: UserDao: 查询项目:2失败,(mysql.connector.errors.ProgrammingError) 1054 (42S22): Unknown column 'project.app' in 'field list'
[SQL: SELECT project.id AS project_id, project.name AS project_name, project.owner AS project_owner, project.app AS project_app, project.created_at AS project_created_at, project.updated_at AS project_updated_at, project.deleted_at AS project_deleted_at, project.create_user AS project_create_user, project.update_user AS project_update_user, project.private AS project_private, project.description AS project_description 
FROM project 
WHERE project.id = %(id_1)s AND project.deleted_at IS NULL 
 LIMIT %(param_1)s]
[parameters: {'id_1': '2', 'param_1': 1}]
(Background on this error at: http://sqlalche.me/e/14/f405)
[2023-03-12 10:50:09.702283] ERROR: UserDao: 获取用户:1项目列表失败, [Errno 22] Invalid argument
[2023-03-12 10:54:02.420374] ERROR: UserDao: 获取用户:1项目列表失败, [Errno 22] Invalid argument
[2023-03-12 19:59:20.255104] ERROR: UserDao: 获取用户:1项目列表失败, [Errno 22] Invalid argument
[2023-03-12 20:00:22.794862] ERROR: UserDao: 获取用户:1项目列表失败, [Errno 22] Invalid argument
[2023-03-12 20:02:36.997512] ERROR: UserDao: 获取用户:1项目列表失败, [Errno 22] Invalid argument
[2023-03-13 07:56:28.323484] ERROR: UserDao: 添加用例失败:(mysql.connector.errors.DatabaseError) 1364 (HY000): Field 'expected' doesn't have a default value
[SQL: INSERT INTO test_case (name, request_type, url, request_method, request_header, body, project_id, tag, `status`, priority, catalogue, created_at, updated_at, deleted_at, create_user, update_user) VALUES (%(name)s, %(request_type)s, %(url)s, %(request_method)s, %(request_header)s, %(body)s, %(project_id)s, %(tag)s, %(status)s, %(priority)s, %(catalogue)s, %(created_at)s, %(updated_at)s, %(deleted_at)s, %(create_user)s, %(update_user)s)]
[parameters: {'name': '1', 'request_type': 1, 'url': '1', 'request_method': 'GET', 'request_header': '{}', 'body': '', 'project_id': 1, 'tag': '1', 'status': 1, 'priority': 'P0', 'catalogue': None, 'created_at': datetime.datetime(2023, 3, 13, 7, 56, 28, 320338), 'updated_at': datetime.datetime(2023, 3, 13, 7, 56, 28, 320338), 'deleted_at': None, 'create_user': 1, 'update_user': 1}]
(Background on this error at: http://sqlalche.me/e/14/4xp6)
[2023-03-13 12:16:03.201575] ERROR: UserDao: 获取用户:1项目列表失败, (mysql.connector.errors.ProgrammingError) 1054 (42S22): Unknown column 'project.app' in 'field list'
[SQL: SELECT count(*) AS count_1 
FROM (SELECT project.id AS project_id, project.name AS project_name, project.owner AS project_owner, project.app AS project_app, project.created_at AS project_created_at, project.updated_at AS project_updated_at, project.deleted_at AS project_deleted_at, project.create_user AS project_create_user, project.update_user AS project_update_user, project.private AS project_private, project.description AS project_description 
FROM project 
WHERE project.deleted_at IS NULL) AS anon_1]
(Background on this error at: http://sqlalche.me/e/14/f405)
[2023-03-13 12:16:12.233157] ERROR: UserDao: 获取用户:1项目列表失败, (mysql.connector.errors.ProgrammingError) 1054 (42S22): Unknown column 'project.app' in 'field list'
[SQL: SELECT count(*) AS count_1 
FROM (SELECT project.id AS project_id, project.name AS project_name, project.owner AS project_owner, project.app AS project_app, project.created_at AS project_created_at, project.updated_at AS project_updated_at, project.deleted_at AS project_deleted_at, project.create_user AS project_create_user, project.update_user AS project_update_user, project.private AS project_private, project.description AS project_description 
FROM project 
WHERE project.deleted_at IS NULL) AS anon_1]
(Background on this error at: http://sqlalche.me/e/14/f405)
[2023-03-14 07:38:20.006621] ERROR: UserDao: 执行用例失败:module 'app.dao.test_case.TestCaseDao' has no attribute 'query_test_case'
[2023-03-18 15:20:13.778446] INFO: UserDao: 有人访问你的网站了
[2023-03-18 15:20:14.242493] INFO: UserDao: 有人访问你的网站了
[2023-03-19 14:47:35.825915] ERROR: UserDao: 新增环境:212121212失败,super() argument 1 must be type, not int
[2023-03-19 14:50:51.688292] ERROR: UserDao: 新增环境:432432失败,super() argument 1 must be type, not int
[2023-03-19 14:52:11.348319] ERROR: UserDao: 新增环境:53255失败,(mysql.connector.errors.IntegrityError) 1048 (23000): Column 'created_at' cannot be null
[SQL: INSERT INTO environment (created_at, updated_at, deleted_at, create_user, update_user, id, name, remarks) VALUES (%(created_at)s, %(updated_at)s, %(deleted_at)s, %(create_user)s, %(update_user)s, %(id)s, %(name)s, %(remarks)s)]
[parameters: {'created_at': None, 'updated_at': None, 'deleted_at': None, 'create_user': None, 'update_user': None, 'id': 0, 'name': '53255', 'remarks': ''}]
(Background on this error at: http://sqlalche.me/e/14/gkpj)
[2023-03-19 14:53:19.783669] ERROR: UserDao: 新增环境:434343失败,super() takes no keyword arguments
[2023-03-19 15:13:47.851915] ERROR: UserDao: 新增环境:54354645634失败,(mysql.connector.errors.DataError) 1406 (22001): Data too long for column 'name' at row 1
[SQL: INSERT INTO environment (created_at, updated_at, deleted_at, create_user, update_user, id, name, remarks) VALUES (%(created_at)s, %(updated_at)s, %(deleted_at)s, %(create_user)s, %(update_user)s, %(id)s, %(name)s, %(remarks)s)]
[parameters: {'created_at': datetime.datetime(2023, 3, 19, 15, 13, 47, 812768), 'updated_at': datetime.datetime(2023, 3, 19, 15, 13, 47, 812768), 'deleted_at': None, 'create_user': 1, 'update_user': 1, 'id': 0, 'name': '54354645634', 'remarks': ''}]
(Background on this error at: http://sqlalche.me/e/14/9h9h)
[2023-03-19 16:27:57.584237] ERROR: UserDao: 删除环境失败,'int' object has no attribute 'get'
[2023-03-19 16:28:38.704031] ERROR: UserDao: 删除环境失败,'int' object has no attribute 'get'
[2023-03-21 08:10:13.820207] ERROR: UserDao: 查询失败,count() takes exactly one argument (0 given)
[2023-03-21 08:10:28.969378] ERROR: UserDao: 查询失败,count() takes exactly one argument (0 given)
[2023-03-21 08:11:16.583200] ERROR: UserDao: 查询失败,count() takes exactly one argument (0 given)
[2023-03-21 08:13:56.233562] ERROR: UserDao: 查询失败,count() takes exactly one argument (0 given)
[2023-03-22 16:43:23.930546] ERROR: UserDao: 新增环境:test1失败,Python type builtin_function_or_method cannot be converted
[2023-03-22 16:43:50.450185] ERROR: UserDao: 新增环境:test2失败,Python type builtin_function_or_method cannot be converted
[2023-03-22 17:16:38.786069] ERROR: UserDao: 新增环境:1失败,(mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry '1' for key 'name'
[SQL: INSERT INTO environment (created_at, updated_at, deleted_at, create_user, update_user, id, name, remarks) VALUES (%(created_at)s, %(updated_at)s, %(deleted_at)s, %(create_user)s, %(update_user)s, %(id)s, %(name)s, %(remarks)s)]
[parameters: {'created_at': datetime.datetime(2023, 3, 22, 17, 16, 38, 775052), 'updated_at': datetime.datetime(2023, 3, 22, 17, 16, 38, 775052), 'deleted_at': None, 'create_user': 1, 'update_user': 1, 'id': 0, 'name': '1', 'remarks': ''}]
(Background on this error at: http://sqlalche.me/e/14/gkpj)
[2023-03-22 17:17:56.251613] ERROR: UserDao: 新增环境:1失败,(mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry '1' for key 'name'
[SQL: INSERT INTO environment (created_at, updated_at, deleted_at, create_user, update_user, id, name, remarks) VALUES (%(created_at)s, %(updated_at)s, %(deleted_at)s, %(create_user)s, %(update_user)s, %(id)s, %(name)s, %(remarks)s)]
[parameters: {'created_at': datetime.datetime(2023, 3, 22, 17, 17, 56, 247613), 'updated_at': datetime.datetime(2023, 3, 22, 17, 17, 56, 247613), 'deleted_at': None, 'create_user': 1, 'update_user': 1, 'id': 0, 'name': '1', 'remarks': ''}]
(Background on this error at: http://sqlalche.me/e/14/gkpj)
[2023-03-22 17:18:41.321116] ERROR: UserDao: 新增环境:1失败,(mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry '1' for key 'name'
[SQL: INSERT INTO environment (created_at, updated_at, deleted_at, create_user, update_user, id, name, remarks) VALUES (%(created_at)s, %(updated_at)s, %(deleted_at)s, %(create_user)s, %(update_user)s, %(id)s, %(name)s, %(remarks)s)]
[parameters: {'created_at': datetime.datetime(2023, 3, 22, 17, 18, 41, 317116), 'updated_at': datetime.datetime(2023, 3, 22, 17, 18, 41, 317116), 'deleted_at': None, 'create_user': 1, 'update_user': 1, 'id': 0, 'name': '1', 'remarks': ''}]
(Background on this error at: http://sqlalche.me/e/14/gkpj)
